//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_admin_log
    {
        public int id { get; set; }
        public System.DateTime action_time { get; set; }
        public int user_id { get; set; }
        public Nullable<int> content_type_id { get; set; }
        public string object_id { get; set; }
        public string object_repr { get; set; }
        public short action_flag { get; set; }
        public string change_message { get; set; }
    
        public virtual User User { get; set; }
        public virtual auth_content_type auth_content_type { get; set; }
    }
}
