//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_content_type
    {
        public auth_content_type()
        {
            this.auth_admin_log = new HashSet<auth_admin_log>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string app_label { get; set; }
        public string model { get; set; }
    
        public virtual ICollection<auth_admin_log> auth_admin_log { get; set; }
    }
}
