//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakingNew
    {
        public int ID { get; set; }
        public string Note { get; set; }
        public bool Enabled { get; set; }
        public int BreakingNewsTypeID { get; set; }
        public byte ClientID { get; set; }
        public int Repeat { get; set; }
        public byte NumberOfGraphicsBetween { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<byte> SortOrder { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public Nullable<byte> ExpiresIn { get; set; }
        public Nullable<int> ExpirationMode { get; set; }
        public string IntroText { get; set; }
        public string HeaderText { get; set; }
        public string HeaderImage { get; set; }
        public string TopicMovie { get; set; }
        public string ColorHex { get; set; }
        public string IntroMovie { get; set; }
        public string TopicText { get; set; }
        public string HeaderMovie { get; set; }
    
        public virtual BreakingNewsType BreakingNewsType { get; set; }
        public virtual Client Client { get; set; }
    }
}
