//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakingNewsType
    {
        public BreakingNewsType()
        {
            this.BreakingNews = new HashSet<BreakingNew>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<BreakingNew> BreakingNews { get; set; }
    }
}
