//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTeam
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int TeamID { get; set; }
        public string AltAbbreviation { get; set; }
        public string AltCityName { get; set; }
        public string AltNickName { get; set; }
        public string AltPrimaryColor { get; set; }
        public string AltSecondaryColor { get; set; }
        public Nullable<int> AltRanking { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
