//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupGame
    {
        public int ID { get; set; }
        public string HiveID { get; set; }
        public int GroupID { get; set; }
        public Nullable<int> GameID { get; set; }
        public int SportID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string SDMLeagueCode { get; set; }
        public Nullable<int> DataSource { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Group Group { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
