//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaguesSetting
    {
        public int Id { get; set; }
        public int ClientID { get; set; }
        public string LeagueCode { get; set; }
        public Nullable<int> SettingsID { get; set; }
        public Nullable<int> OptionsID { get; set; }
    }
}
