//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistDetail
    {
        public int ID { get; set; }
        public int PlaylistID { get; set; }
        public byte EntryTypeID { get; set; }
        public int EntryID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string OnAirName { get; set; }
        public string HiveID { get; set; }
        public Nullable<byte> RipCount { get; set; }
        public Nullable<byte> NotesTypeID { get; set; }
        public Nullable<int> RipGameStatusTypeID { get; set; }
        public string SDMLeagueCode { get; set; }
        public string Specifics1 { get; set; }
        public Nullable<int> DataSource { get; set; }
    
        public virtual Playlist Playlist { get; set; }
    }
}
