//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.Status = new HashSet<Status>();
            this.Games = new HashSet<Game>();
            this.Teams = new HashSet<Team>();
            this.ClientSports = new HashSet<ClientSport>();
            this.Teams1 = new HashSet<Team>();
            this.GroupGames = new HashSet<GroupGame>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string ShortDisplay { get; set; }
        public string LongDisplay { get; set; }
        public string StatsIncName { get; set; }
        public Nullable<int> KeepResultsInDays { get; set; }
        public string SportType { get; set; }
        public string DisplayField { get; set; }
        public string GameFrequency { get; set; }
        public string HivePrefix { get; set; }
    
        public virtual ICollection<Status> Status { get; set; }
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<ClientSport> ClientSports { get; set; }
        public virtual ICollection<Team> Teams1 { get; set; }
        public virtual ICollection<GroupGame> GroupGames { get; set; }
    }
}
