//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.ClientTeams = new HashSet<ClientTeam>();
        }
    
        public int ID { get; set; }
        public int StatsIncID { get; set; }
        public int SportID { get; set; }
        public string Abbreviation { get; set; }
        public string CityName { get; set; }
        public string NickName { get; set; }
        public string PrimaryColor { get; set; }
        public string SecondaryColor { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Loss { get; set; }
        public Nullable<int> Tie { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual ICollection<ClientTeam> ClientTeams { get; set; }
        public virtual Sport Sport1 { get; set; }
    }
}
