//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Client : global::System.Configuration.ApplicationSettingsBase {
        
        private static Client defaultInstance = ((Client)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Client())));
        
        public static Client Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Fox Ticker\\Clients\\FSN\\Ventuz\\Movies\\Intro")]
        public string IntroMoviePath {
            get {
                return ((string)(this["IntroMoviePath"]));
            }
            set {
                this["IntroMoviePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Fox Ticker\\Clients\\FSN\\Elements\\Sponsors")]
        public string SponsorPath {
            get {
                return ((string)(this["SponsorPath"]));
            }
            set {
                this["SponsorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FOXSPORTS.COM on msn.avi")]
        public string IntroMovieDefault {
            get {
                return ((string)(this["IntroMovieDefault"]));
            }
            set {
                this["IntroMovieDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TF-NFLonFOX.tga")]
        public string SponsorDefault {
            get {
                return ((string)(this["SponsorDefault"]));
            }
            set {
                this["SponsorDefault"] = value;
            }
        }
    }
}
